% This example demonstrated the basic of MPI signal generation using the
% example described in the Ph.D. Thesis from S. Biederer untitled:
% "Entwicklung eines Spektrometers zur Analyse superparamagnetischer Eisenoxid-Nanopartikel für Magnetic-Particle-Imaging"

close all
clear all
addpath('coreFunctions\')


for kkk=1:10
    
mu0 = 4*pi*1e-7; % permeability of the air.
c = 0.03*0.500*1000; % [mol(Fe)/m^3] Using Resovist, with the assumption that only 3% of the iron is usefull to the signal
v = 10*10^-9; %[m^3] volume of the test sample (10 µl) (page 99 of the thesis)
d = 30*10^-9; % [m] diameter of the particle. From the thesis. P98.
Ms = 0.6/mu0; %[A/m] Magnetisation at saturation from Magnetit. From the thesis. P54
temperature = 310;
Fs          = kkk*10^6;%2.5e7; % [Hz] sampling frequency
f           = 25000; % [Hz] Frequency of the signal
nbrPeriod   = 10; % nbr of signal period
t           = 0:1/Fs:nbrPeriod/f; % [s] time vector
N           = length(t); %Number of time points
H0          = 31831;% [A/m] Drive field amplitude (31831 A/m to generate 40 mT)
B0          = H0*mu0; % [T] - H = B/mu
%% Particle Magnetization in function of the applied magnetic field

nbrPoint = 1000;
a=zeros(nbrPoint,1);
mu0 = 4*pi*1e-7; % permeability of the air.
Hpart=linspace(-10000,10000,nbrPoint);
Bpart = Hpart.*mu0;
Mpart=zeros(nbrPoint,1);
for n=1:nbrPoint,
  [Mpart(n),~,~,a(n)] = langevinParticle3( Bpart(n),0,0,abs(Bpart(n)), d,Ms,temperature,c,v);

end
figure
subplot(2,3,1)
hold off
plot(Bpart, Mpart, 'k');
xlim([-max(Bpart) max(Bpart)])
xlabel('B / (T)')
ylabel('M / (A/m)')
title('Particle magnetisation curve');

%% Drive field Amplitude in function of the time
H=H0*sin(2*pi*f*t);
B = H.*mu0;

subplot(2,3,4)
plot(t,B,'k');
xlabel('t / s')
ylabel('B / (T)')
title(sprintf('Drive field amplitude: %0.2g mT peak',B0*1000));

%% Particle Magnetization in function of the time
M=zeros(N,1);
for n=1:N,
  [M(n),~,~,~] = langevinParticle3( B(n),0,0,abs(B(n)), d,Ms,temperature,c,v);
end

subplot(2,3,2)
plot(t, M, 'k');
xlabel('t / s')
ylabel('M / (A/m)')
title('Particle Magnetisation');

% Time signal
% According to Knopp "introduction into MPI" pdf 35 equ 2.36
%we assume that the sensibility is constante in this voxel
% the sensibilte is there define as the field generated by a 1A current
s = 1366*mu0; % [T/A] From the thesis. P98. Eq. 4.67

% We have to calculate the derivative, that is what happens after a small
% time
dT= t(2)-t(1);

% noise model
kB  = 1.380650424e-23; % [J/K] Boltzmann constant 
deltaF = 10*10^6; % [Hz] according to Weizenecker 2007 - A simulation study...
Rp = 185 *10^-3; % [Ohm]  according to Weizenecker 2007 - A simulation study...
Umax = 1*sqrt(4*kB*temperature*deltaF*Rp);% [V]
u=zeros(N,1);
for n=2:N,
	u(n) = s*(M(n)-M(n-1)) / dT + normrnd(0,Umax);
end

umax(kkk) = max(u);
subplot(2,3,3)
plot(t, u, 'k');
xlabel('t / s')
ylabel('u / V')
title('Time signal');

%% Spectrum

fStart = 2;
fStop = 500;

subplot(2,3,6)
periodogram = fft(u);
uhat = abs(2*periodogram(1:(end-1)/2+1));
Fs = 1/(t(2)-t(1));
freq = Fs/2*linspace(0,1,length(u)/2+1);
%semilogy(freq(fStart:fStop)/f,real(uhat(fStart:fStop)), 'o');
title('Spectrum - # of harmonic');
xlim([ 0 50])
end

close all
figure
plot(umax)
xlabel('Sampling frequency /MHz')
ylabel('Simulated Umax(have to be around 6 mV')